#%RAML 0.8
title: Holonic MDM API
version: v1
#baseUri: http://mdm.io/mes/api/{version}
baseUri: http://127.0.0.1:5000
mediaType: application/json
documentation:
  - title: Holonic MDM API
    content: ""

schemas:
  - Facility: !include json/commons-material-schema.json
  - Facilities: !include json/commons-materials-schema.json
  - Inventory: !include json/commons-material-schema.json
  - Inventories: !include json/commons-materials-schema.json
  - Schedule: !include json/commons-material-schema.json
  - Schedules: !include json/commons-materials-schema.json
  - Error: !include json/commons-error-schema.json
  - Message: !include json/commons-message-schema.json

/schedule:

/facility:

/inventories:
  get:
    description: Get a list of Inventories
    responses:
      200:
        body:
          application/json:
            schema: Inventories
  post:
    description: Add new Inventory
    body:
      application/json:
        schema: Inventory
    responses:
      201:
        body:
          application/json:
            schema: Inventory
  /{resourceId}:
    get:
      description: Get a Inventory by ID
      responses:
        200:
          body:
            application/json:
              schema: Inventory
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Inventory by ID
      body:
        application/json:
          schema: Inventory
      responses:
        200:
          body:
            application/json:
              schema: Inventory
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Inventory by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

  /materials:
    get:
      description: Get a list of Materials
      responses:
        200:
          body:
            application/json:
              schema: Inventories
    post:
      description: Add new Material
      body:
        application/json:
          schema: Inventory
      responses:
        201:
          body:
            application/json:
              schema: Inventory
    /{resourceId}:
      get:
        description: Get a Material by ID
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      put:
        description: Update Material by ID
        body:
          application/json:
            schema: Inventory
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      delete:
        description: Delete a Material by ID
        responses:
          204:
          404:
            body:
              application/json:
                schema: Error

  /components:
    get:
      description: Get a list of Components
      responses:
        200:
          body:
            application/json:
              schema: Inventories
    post:
      description: Add new Component
      body:
        application/json:
          schema: Inventory
      responses:
        201:
          body:
            application/json:
              schema: Inventory
    /{resourceId}:
      get:
        description: Get a Component by ID
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      put:
        description: Update Component by ID
        body:
          application/json:
            schema: Inventory
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      delete:
        description: Delete a Component by ID
        responses:
          204:
          404:
            body:
              application/json:
                schema: Error

  /products:
    get:
      description: Get a list of Products
      responses:
        200:
          body:
            application/json:
              schema: Inventories
    post:
      description: Add new Product
      body:
        application/json:
          schema: Inventory
      responses:
        201:
          body:
            application/json:
              schema: Inventory
    /{resourceId}:
      get:
        description: Get a Product by ID
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      put:
        description: Update Product by ID
        body:
          application/json:
            schema: Inventory
        responses:
          200:
            body:
              application/json:
                schema: Inventory
          404:
            body:
              application/json:
                schema: Error
      delete:
        description: Delete a Product by ID
        responses:
          204:
          404:
            body:
              application/json:
                schema: Error
